name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repo
      #   uses: actions/checkout@v2

      # - uses: pnpm/action-setup@v2.0.1
      #   with:
      #     version: 8.6.7

      # - name: Setup Node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 20

      - name: Checkout Code
        uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.7
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"
      # - run: pnpm install

      - name: Install dependencies
        # uses: bahmutov/npm-install@v1
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist